#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat 

mcr.microsoft.com/dotnet/aspnet:5.0 AS base


FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build 
WORKDIR /src 
COPY WebApplication1.csproj . 
RUN dotnet restore 
COPY . . 
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:5.0 
WORKDIR /app COPY --from=build /app . 
ENTRYPOINT ["dotnet", "WebApplication1.dll"]
