apiVersion: v1
kind: Service
metadata:
    name: "hostelaks-cb87"
    labels:
        app: "hostelaks-cb87"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "hostelaks-cb87"