on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: hostelacs.azurecr.io
        username: ${{ secrets.acr_hostelacs_username }}
        password: ${{ secrets.acr_hostelacs_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/WebApplication1" -f  "WebApplication1/Dockerfile" -t hostelacs.azurecr.io/hostelaks:${{ github.sha }} --label dockerfile-path=WebApplication1/Dockerfile
        docker push hostelacs.azurecr.io/hostelaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_hostelaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep hostelaksa8a6 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace hostelaksa8a6`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: hostelaksa8a6
        container-registry-url: hostelacs.azurecr.io
        container-registry-username: ${{ secrets.acr_hostelacs_username }}
        container-registry-password: ${{ secrets.acr_hostelacs_password }}
        secret-name: hostelaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: hostelaksa8a6
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          hostelacs.azurecr.io/hostelaks:${{ github.sha }}
        imagepullsecrets: |
          hostelaksdockerauth
